# class Student:
#        def __init__(self,name,marks):
#         self.name = name
#         self.marks = marks
        
#         def get_avg(self):
#                sum = 0
#                for val in marks:
#                       sum+=val
#                print("hi",self.name,"your avg of marks is: ",sum/3)
# s1 = Student("tony stark",[99,98,97])


# s1.get_avg()


def table(n,i):
 if i==11:
  return 0
 else:
     print(num*i)  
